version: "3.1"

services:
  postgres:
    container_name: ${DB_HOST}
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  webserver:
    image: altimofeev/webserver-localhost
    working_dir: ${WORKDIR}
    ports:
      - ${APP_PORT}:80
    depends_on:
      - app
    volumes:
      - ./:${WORKDIR}
      - sock_test:${SOCKET_DIR}

  app:
    image: altimofeev/php8.0-fpm
    env_file:
      - .env
    working_dir: ${WORKDIR}
    volumes:
      - ./:${WORKDIR}
      - sock_test:${SOCKET_DIR}

volumes:
  sock_test:
